config/routes.rb
Rails.application.routes.draw do
  root to: 'roadworks#index'

  resources :roadworks, only: [:index, :show, :new, :create] do
    resources :projects, only: [:create]
  end
  resources :projects, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :roadwork

  validates :name, presence: true, uniqueness: { scope: :roadwork_id }
  validates :image_url, presence: true
  validates_format_of :image_url, :with => /(https?:\/\/.*\.(?:png|jpg|jpeg|img|gif))/i, message: " Bien essayé mais ce n'est pas un IMAGE !"
end

app/models/roadwork.rb
class Roadwork < ApplicationRecord

  has_many :projects, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :banner_url, presence: true
  validates_format_of :banner_url, :with => /(https?:\/\/.*\.(?:png|jpg|jpeg|img|gif))/i, message: " Bien essayé mais ce n'est pas un IMAGE !"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects.rb
class projectsController < ApplicationController
  def create
    @roadwork = Roadwork.find(params[:roadwork_id])
    @project = Project.new(project_params)
    @project.roadwork = @roadwork
    if @project.save
      redirect_to roadwork_path(@roadwork)
    else
      render 'roadworks/show'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @roadwork = @project.roadwork
    @project.destroy
    redirect_to roadwork_path(@roadwork)
  end

  private

  def project_params
    params.require(:project).permit(:name, :image_url)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def create
    @roadwork = Roadwork.find(params[:roadwork_id])
    @project = Project.new(project_params)
    @project.roadwork = @roadwork
    if @project.save
      # Deliver the signup email
      NotificationMailer.create_project(@project).deliver
      redirect_to roadwork_path(@roadwork, :notice => 'Projet créé')
    else
      render 'roadworks/show'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @roadwork = @project.roadwork
    @project.destroy
    redirect_to roadwork_path(@roadwork)
  end

  private

  def project_params
    params.require(:project).permit(:name, :image_url)
  end
end

app/controllers/roadworks_controller.rb
class RoadworksController < ApplicationController
  def index
    @roadworks = Roadwork.all
  end

  def show
    @roadwork = Roadwork.find(params[:id])
    @project = Project.new
    @projects = @roadwork.projects
  end

  def new
    @roadwork = Roadwork.new
  end

  def create
    @roadwork = Roadwork.new(roadwork_params)
    if @roadwork.save
      redirect_to roadwork_path(@roadwork)
    else
      render :new
    end
  end

  private

  def roadwork_params
    params.require(:roadwork).permit(:name, :banner_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Batiment et Travaux</title>
    <!-- Hotjar Tracking Code for http://www.jetlife.best -->
    <script>
      (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:1849642,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
      })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
    </script>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag asset_path('logo.png') %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render "shared/navbar" %>
    <div class="content">
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
    <!-- WARNING: DO NOT DELETE THE LINE BELOW -->
    <div id="rails-roadwork-manager-watermark"></div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/roadworks/_garden_card.html.erb
<%= link_to roadwork_path(roadwork) do %>
  <div class="card-roadwork">
    <%= image_tag roadwork.banner_url %>
    <div class="card-roadwork-infos">
      <div>
        <h2><%= roadwork.name %></h2>
      </div>
    </div>
  </div>
<% end %>

app/views/roadworks/_plant_card.html.erb
<div class="card-project" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= project.image_url %>)">
  <%= project.name %>
  <%= link_to "+", project_path(project), method: :delete, data: { confirm: "Are you sure?" }, class: "card-remove-link" %>
</div>

app/views/roadworks/_project_card.html.erb
<div class="card-project" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= project.image_url %>)">
  <%= project.name %>
  <%= link_to "+", project_path(project), method: :delete, data: { confirm: "Are you sure?" }, class: "card-remove-link" %>
</div>

app/views/roadworks/_roadwork_card.html.erb
<%= link_to roadwork_path(roadwork) do %>
  <div class="card-roadwork">
    <%= image_tag roadwork.banner_url %>
    <div class="card-roadwork-infos">
      <div>
        <h2><%= roadwork.name %></h2>
      </div>
    </div>
  </div>
<% end %>

app/views/roadworks/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url(<%= image_path('home_banner.jpg') %>)">
  <div class="container">
    <h1>Mon gestionnaire de travaux</h1>
    <p>Postez, Gérez et Optimisez vos recherche d'artisants pour travaux</p>
    <%= link_to "Découvrir", "#how", class: "btn btn-flat" %>
  </div>
</div>

<div class="container">
  <div class="section">
    <h2 id="how" class="text-center">Comment cela fonctionne?</h2>
    <div class="row">
      <div class="col-xs-12 col-md-6 col-lg-4">
        <%= link_to new_roadwork_path do %>
          <div class="icon">
            <%= image_tag "roadwork.svg" %>
          </div>
        <% end %>
        <p class="text-center fs-24">Créez votre projet de travaux</p>
      </div>
      <div class="col-xs-12 col-md-6 col-lg-4">
        <%= link_to new_roadwork_path do %>
          <div class="icon">
            <%= image_tag "circles.svg" %>
          </div>
        <% end %>
        <p class="text-center fs-24">Ajoutez les détails et précisions</p>
      </div>
      <div class="col-xs-12 col-md-6 col-lg-4">
        <%= link_to new_roadwork_path do %>
          <div class="icon">
            <%= image_tag "watering.svg" %>
          </div>
        <% end %>
        <p class="text-center fs-24">Gérez vos demandes et le suivis</p>
      </div>
    </div>
  </div>
  <div class="section">
    <h2 class="text-center">La Meilleure Communauté pour travaux</h2>
    <div class="cards">
      <% @roadworks.each do |roadwork| %>
        <%= render "roadwork_card", roadwork: roadwork %>
      <% end %>
    </div>
  </div>
  <div class="section">
    <div class="text-center">
      <%= link_to "Créer mon projet", new_roadwork_path, class: "btn btn-flat" %>
    </div>
  </div>
</div>

app/views/roadworks/new.html.erb
<div class="pt-30 container">
  <h1 class="text-center">Nouveau projet</h1>
  <div class="row justify-content-center">
    <div class="col-6">
      <%= simple_form_for(@roadwork) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-inputs">
        <%= f.input :name, label:"Nom du projet" %>
        <!-- <%#= f.input :banner_url, label:"Photo d'illustration", as: :file %> -->
        <%= f.input :banner_url, label:"Photo d'illustration" %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, value:"Poster votre projet", class: "btn btn-flat" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/roadworks/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= @roadwork.banner_url %>');">
  <div class="container">
    <h1><%= @roadwork.name %></h1>
  </div>
</div>

<div class="pt-30 container">
  <div class="cards">
    <% @roadwork.projects.each do |project| %>
      <%= render "roadworks/project_card", project: project %>
    <% end %>
  </div>
  <div class="pt-30 row justify-content-center">
    <div class="col-12 col-md-4">
      <h4 class="text-center">Add a project</h4>
      <%= simple_form_for [ @roadwork, @project ] do |f| %>
        <%= f.input :name, placeholder: "Palm tree" %>
        <%= f.input :image_url, placeholder: "https://some_nice_image_found_on_google.jpg" %>
        <div class="form-actions">
          <%= f.submit "Add", class: "btn btn-flat" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Footer made with <i class="fas fa-heart"></i> by <a href="https://github.com/nlabrazi">Nabil</a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <div class="logo">
      <%= image_tag "roadwork.svg" %>
    </div>
  <% end %>
</div>